"""Manifest format for ./run apps. See docs/domain.md.

parse_manifest / format_manifest own the apps.manifest file format.
"""

from __future__ import annotations

from .apps import is_valid_bundle_id


def parse_manifest(text: str) -> dict[int, str]:
    """Parse a manifest file text into {index: bundle_id}.

    Skips comment lines, blank lines, lines without '=', non-integer indices,
    and lines whose bundle ID fails the restricted-charset check.
    Duplicate indices: last line wins.
    """
    result: dict[int, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        idx_part, _, bundle_part = line.partition("=")
        idx_str = idx_part.strip()
        bundle_id = bundle_part.strip()
        if not idx_str.isdigit():
            continue
        if not is_valid_bundle_id(bundle_id):
            continue
        result[int(idx_str)] = bundle_id
    return result


def format_manifest(index_to_bundle_id: dict[int, str]) -> str:
    """Render a manifest dict as file text (indices sorted ascending)."""
    lines = ["# generated by ./run apps — re-run when your running apps change"]
    for idx in sorted(index_to_bundle_id):
        lines.append(f"{idx}={index_to_bundle_id[idx]}")
    return "\n".join(lines) + "\n"
